<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'PHPQueue' => array($vendorDir . '/coderkungfu/php-queue/src'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'Mail_mimeDecode' => array($vendorDir . '/pear/mail_mime-decode'),
    'Mail' => array($vendorDir . '/pear/mail', $vendorDir . '/pear/mail_mime'),
    'Liuggio' => array($vendorDir . '/liuggio/statsd-php-client/src'),
    'Less' => array($vendorDir . '/oyejorge/less.php/lib'),
    'ForceUTF8\\' => array($vendorDir . '/neitanod/forceutf8/src'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
    'ComposerVendorHtaccessCreator' => array($baseDir . '/includes/composer'),
    'ComposerHookHandler' => array($baseDir . '/includes/composer'),
    'Clio' => array($vendorDir . '/clio/clio/src'),
    '' => array($vendorDir . '/cssjanus/cssjanus/src', $vendorDir . '/pear/pear-core-minimal/src'),
);
